In [ ]:
# --- project bootstrap (added during repo consolidation) ---
# Resolves the project root so the notebook runs from notebooks/ or from the repo root,
# and puts src/ on sys.path so `import laptop_price` works.
import os, sys, pathlib

_here = pathlib.Path.cwd()
for _cand in (_here, *_here.parents):
    if (_cand / "pyproject.toml").exists():
        PROJECT_ROOT = _cand
        break
else:
    raise RuntimeError("pyproject.toml not found - run this notebook inside the repo")

os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT / "src"))
print(f"project root: {PROJECT_ROOT}")

# Imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Association Rules Mining

This notebook applies the **Apriori** and **FP-Growth** algorithms to discover frequent patterns in laptop configurations. The goal is to identify which hardware specifications commonly appear together, revealing market segments and product bundling opportunities.

**Algorithms Used:**
- **Apriori**: Classic bottom-up approach for finding frequent itemsets
- **FP-Growth**: More efficient tree-based approach 

**Parameters:**
- Minimum Support: 5%
- Minimum Confidence: 60%

In [ ]:
# Load the FULLY cleaned dataset (data2026)
df = pd.read_csv('data/processed/pre_processed_data.csv')

In [ ]:
# list the columns and the number of distinct vlues for each column
print("\nDataset columns:")
print(df.columns.to_list())

Dataset columns:
['id', 'price_preview', 'created_at', 'city', 'spec_Etat', 'model_name', 'DEDICATED_GPU', 'CPU', 'RAM_SIZE', 'SSD_SIZE', 'HDD_SIZE', 'SCREEN_SIZE', 'SCREEN_RESOLUTION', 'RAM_TYPE', 'mapped_cpu_name', 'match_score', 'cores', 'cpu_mark', 'tdp', 'gpu_name', 'match_type', 'gpu_match_score', 'gpu_g3d_mark', 'gpu_g2d_mark', 'gpu_tdp', 'cpu_manufacturer', 'cpu_family', 'cpu_generation_raw', 'cpu_family_type', 'cpu_generation_normalized', 'SCREEN_SIZE_SNAPPED', 'SCREEN_RESOLUTION_STD', 'SCREEN_RESOLUTION_ENC', 'price_corrected']

### Data Overview

The dataset contains **16,392 laptop listings** with various hardware specifications. For association rule mining, we need to:
1. Convert continuous variables (RAM, storage, price) into categorical bins
2. One-hot encode categorical features (brand, condition, screen resolution)
3. Remove high-cardinality columns that would create sparse itemsets

In [ ]:
# remove the following columns from all three datasets (if they exist)
columns_to_remove = ['SCREEN_SIZE', 'SCREEN_RESOLUTION', 'SCREEN_RESOLUTION_ENC', 'price_preview', 'match_score', 
                     'match_type', 'gpu_match_score', 'cpu_generation_normalized', 'created_at', 'CPU', 
                     'DEDICATED_GPU', 'gpu_g3d_mark', 'gpu_g2d_mark', 'gpu_tdp', 'cpu_manufacturer', 'cpu_family',
                     'cpu_mark', 'tdp','city', 'cpu_mfg_AMD', 'cpu_mfg_Apple', 'cpu_mfg_Intel', 'cpu_mfg_Other', 
                     'cpu_mfg_Qualcomm', 'cpu_mfg_Unknown']
df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

# rename some columns for better clarity
df.rename(columns={'SCREEN_SIZE_SNAPPED': 'screen_size',
                   'SCREEN_RESOLUTION_STD': 'screen_resolution',
                   'price_corrected': 'price',
                   'cpu_generation_raw': 'cpu_generation',
                   'RAM_SIZE': 'ram_size', 
                   'SSD_SIZE': 'ssd_size', 
                   'HDD_SIZE': 'hdd_size', 
                   'RAM_TYPE': 'ram_type'
                   }, inplace=True)


# list the columns and the number of distinct vlues for each column
print("\nDataset columns:")
print(df.columns.to_list())

print("\nDataset columns and number of distinct values:")
print("-" * 50)
for col in df.columns:
    num_unique = df[col].nunique()
    print(f"{col}: {num_unique} distinct values")

# number of columns
print("-" * 50)
print("Number of columns:", len(df.columns))

Dataset columns:
['id', 'spec_Etat', 'model_name', 'ram_size', 'ssd_size', 'hdd_size', 'ram_type', 'mapped_cpu_name', 'cores', 'gpu_name', 'cpu_generation', 'cpu_family_type', 'screen_size', 'screen_resolution', 'price']

Dataset columns and number of distinct values:
--------------------------------------------------
id: 16392 distinct values
spec_Etat: 3 distinct values
model_name: 46 distinct values
ram_size: 27 distinct values
ssd_size: 116 distinct values
hdd_size: 77 distinct values
ram_type: 19 distinct values
mapped_cpu_name: 643 distinct values
cores: 9 distinct values
gpu_name: 151 distinct values
cpu_generation: 15 distinct values
cpu_family_type: 4 distinct values
screen_size: 30 distinct values
screen_resolution: 9 distinct values
price: 937 distinct values
--------------------------------------------------
Number of columns: 15

In [ ]:
# change the vlues of 'spec_Etat'
# map 'BON TAT' to 'Bon_état', 'JAMAIS UTILIS' to 'jamais_utilisé', and 'MOYEN' to 'moyen'
df['spec_Etat'] = df['spec_Etat'].replace({
    'BON TAT': 'Bon_état',
    'JAMAIS UTILIS': 'jamais_utilisé',
    'MOYEN': 'moyen'
})

# One-hot encode spec_Etat using its values as column names, then drop original column
if 'spec_Etat' in df.columns:
    spec_etat_dummies = pd.get_dummies(df['spec_Etat'], dummy_na=False)

    # Rename all dummy columns based on their values (normalize to clean strings)
    spec_etat_dummies = spec_etat_dummies.rename(columns=lambda c: str(c).strip())

    df = pd.concat([df.drop(columns=['spec_Etat']), spec_etat_dummies], axis=1)

# now display the columns of df to verify the changes
print("\nUpdated dataset columns after mapping and encoding:")      
print(df.columns.to_list())
# diplay the number of ones in each of the new columns created from one-hot encoding
print("\nNumber of ones in each one-hot encoded column:")
for col in spec_etat_dummies.columns:
    num_ones = df[col].sum()
    print(f"{col}: {num_ones} ones")

Updated dataset columns after mapping and encoding:
['id', 'model_name', 'ram_size', 'ssd_size', 'hdd_size', 'ram_type', 'mapped_cpu_name', 'cores', 'gpu_name', 'cpu_generation', 'cpu_family_type', 'screen_size', 'screen_resolution', 'price', 'Bon_état', 'jamais_utilisé', 'moyen']

Number of ones in each one-hot encoded column:
Bon_état: 5254 ones
jamais_utilisé: 4047 ones
moyen: 293 ones

In [ ]:
# display distinct values of model_name
if 'model_name' in df.columns:
    print("\nDistinct values in 'model_name' column:")
    print(df['model_name'].unique())  

    # One-hot encode model_name using its values as column names, then drop original column
    model_name_dummies = pd.get_dummies(df['model_name'], dummy_na=False)
    model_name_dummies = model_name_dummies.rename(columns=lambda c: str(c).strip())
    df = pd.concat([df.drop(columns=['model_name']), model_name_dummies], axis=1)

# display the columns of df to verify the changes
print("\nUpdated dataset columns after one-hot encoding 'model_name':")
print(df.columns.to_list())

Distinct values in 'model_name' column:
['IDEAPAD' 'AERO' 'STEALTH' 'ROG' nan 'XPS' 'THINKPAD' 'LATITUDE' 'SWORD'
 'PAVILION' 'ELITEBOOK' 'MACBOOK' 'VIVOBOOK' 'INSPIRON' 'PROBOOK' 'ASPIRE'
 'VECTOR' 'SPECTRE' 'LEGION' 'NITRO' 'OMEN' 'ALIENWARE' 'TUF' 'GALAXY'
 'ZBOOK' 'SURFACE' 'BLADE' 'MAC' 'ZENBOOK' 'PRECISION' 'YOGA' 'PREDATOR'
 'STRIX' 'IMAC' 'KATANA' 'VICTUS' 'ENVY' 'THINKBOOK' 'TRAVELMATE' 'GF'
 'VOSTRO' 'SWIFT' 'SPIN' 'OPTIPLEX' 'DYNABOOK' 'TRANSFORMER' 'COMPAQ']

Updated dataset columns after one-hot encoding 'model_name':
['id', 'ram_size', 'ssd_size', 'hdd_size', 'ram_type', 'mapped_cpu_name', 'cores', 'gpu_name', 'cpu_generation', 'cpu_family_type', 'screen_size', 'screen_resolution', 'price', 'Bon_état', 'jamais_utilisé', 'moyen', 'AERO', 'ALIENWARE', 'ASPIRE', 'BLADE', 'COMPAQ', 'DYNABOOK', 'ELITEBOOK', 'ENVY', 'GALAXY', 'GF', 'IDEAPAD', 'IMAC', 'INSPIRON', 'KATANA', 'LATITUDE', 'LEGION', 'MAC', 'MACBOOK', 'NITRO', 'OMEN', 'OPTIPLEX', 'PAVILION', 'PRECISION', 'PREDATOR', 'PROBOOK', 'ROG', 'SPECTRE', 'SPIN', 'STEALTH', 'STRIX', 'SURFACE', 'SWIFT', 'SWORD', 'THINKBOOK', 'THINKPAD', 'TRANSFORMER', 'TRAVELMATE', 'TUF', 'VECTOR', 'VICTUS', 'VIVOBOOK', 'VOSTRO', 'XPS', 'YOGA', 'ZBOOK', 'ZENBOOK']

### RAM and Storage Discretization

**RAM Distribution:**
- 12-18GB: 7,530 (46%) - Most common, standard for modern laptops
- 6-10GB: 6,015 (37%) - Budget segment

**SSD Distribution:**
- 257-512GB: 6,328 (39%) - Sweet spot configuration

**HDD Observation:** 92% of listings have no HDD, confirming the SSD-dominant market.

In [ ]:
# Normalize and bucketize ram_size, then one-hot encode
if 'ram_size' in df.columns:
    # extract numeric value and unit (GB/MB), convert to GB
    ram_str = df['ram_size'].astype(str).str.strip().str.upper()
    ram_num = ram_str.str.extract(r'(\d+(?:\.\d+)?)')[0].astype(float)
    is_mb = ram_str.str.contains('MB', na=False)
    ram_gb = ram_num.where(~is_mb, ram_num / 1024)
    
    # define bins and labels
    bins = [-np.inf, 2, 4, 10, 18, 30, 64, np.inf]
    labels = ['<2GB', '2-4GB', '6-10GB', '12-18GB', '20-30GB', '32-64GB', '>64GB']
    df['ram_size_class'] = pd.cut(ram_gb, bins=bins, labels=labels, right=True)
    df['ram_size_class'] = df['ram_size_class'].astype(object).where(df['ram_size_class'].notna(), 'Unknown')
    
    # one-hot encode and drop original column
    ram_dummies = pd.get_dummies(df['ram_size_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['ram_size']), ram_dummies], axis=1)
    
    print("\nRam size classes and counts:")
    print(ram_dummies.sum().sort_values(ascending=False))

Ram size classes and counts:
12-18GB    7530
6-10GB     6015
32-64GB    1504
2-4GB      1046
<2GB        119
20-30GB      85
Unknown      63
>64GB        30
dtype: int64

In [ ]:
# Normalize and bucketize ssd_size, then one-hot encode
if 'ssd_size' in df.columns:
    # extract numeric value and unit (GB/TB), convert to GB
    ssd_str = df['ssd_size'].astype(str).str.strip().str.upper()
    ssd_num = ssd_str.str.extract(r'(\d+(?:\.\d+)?)')[0].astype(float)
    is_tb = ssd_str.str.contains('TB', na=False)
    ssd_gb = ssd_num.where(~is_tb, ssd_num * 1024)
    
    # define bins and labels (GB)
    ssd_bins = [-np.inf, 128, 256, 512, 1024, 2048, 4096, 8192, np.inf]
    ssd_labels = ['<=128GB', '129-256GB', '257-512GB', '513-1024GB',
                  '1.1-2TB', '2.1-4TB', '4.1-8TB', '>8TB']
    df['ssd_size_class'] = pd.cut(ssd_gb, bins=ssd_bins, labels=ssd_labels, right=True)
    df['ssd_size_class'] = df['ssd_size_class'].astype(object).where(df['ssd_size_class'].notna(), 'Unknown')
    
    # one-hot encode and drop original column
    ssd_dummies = pd.get_dummies(df['ssd_size_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['ssd_size']), ssd_dummies], axis=1)
    
    print("\nSSD size classes and counts:")
    print(ssd_dummies.sum().sort_values(ascending=False))

SSD size classes and counts:
129-256GB     6345
257-512GB     6328
513-1024GB    1697
Unknown       1049
<=128GB        807
1.1-2TB        136
2.1-4TB         18
4.1-8TB          8
>8TB             4
dtype: int64

In [ ]:
# Normalize and bucketize hdd_size, then one-hot encode
if 'hdd_size' in df.columns:
    # extract numeric value and unit (GB/TB), convert to GB
    hdd_str = df['hdd_size'].astype(str).str.strip().str.upper()
    hdd_num = hdd_str.str.extract(r'(\d+(?:\.\d+)?)')[0].astype(float)
    is_tb_hdd = hdd_str.str.contains('TB', na=False)
    hdd_gb = hdd_num.where(~is_tb_hdd, hdd_num * 1024)
    
    # define bins and labels (GB)
    hdd_bins = [-np.inf, 128, 256, 512, 1024, 2048, 4096, 8192, np.inf]
    hdd_labels = ['<=128GB', '129-256GB', '257-512GB', '513-1024GB',
                  '1.1-2TB', '2.1-4TB', '4.1-8TB', '>8TB']
    df['hdd_size_class'] = pd.cut(hdd_gb, bins=hdd_bins, labels=hdd_labels, right=True)
    df['hdd_size_class'] = df['hdd_size_class'].astype(object).where(df['hdd_size_class'].notna(), 'Unknown')
    
    # one-hot encode and drop original column
    hdd_dummies = pd.get_dummies(df['hdd_size_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['hdd_size']), hdd_dummies], axis=1)
    
    print("\nHDD size classes and counts:")
    print(hdd_dummies.sum().sort_values(ascending=False))

HDD size classes and counts:
Unknown       15129
257-512GB       600
513-1024GB      531
129-256GB        80
<=128GB          33
1.1-2TB          16
>8TB              2
2.1-4TB           1
dtype: int64

In [ ]:
# Bucketize price, then one-hot encode (range-based)
if 'price' in df.columns:
    df['price'] = pd.to_numeric(df['price'], errors='coerce')
    price_bins = [-np.inf, 20000, 40000, 60000, 80000, 100000, 150000, 250000, np.inf]
    price_labels = [
        '<=20000',
        '20001-40000',
        '40001-60000',
        '60001-80000',
        '80001-100000',
        '100001-150000',
        '150001-250000',
        '>250000'
    ]
    df['price_class'] = pd.cut(df['price'], bins=price_bins, labels=price_labels, right=True)
    df['price_class'] = df['price_class'].astype(object).where(df['price_class'].notna(), 'Unknown')
    
    price_dummies = pd.get_dummies(df['price_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['price']), price_dummies], axis=1)
    
    print("\nPrice classes and counts:")
    print(price_dummies.sum().sort_values(ascending=False))

Price classes and counts:
100001-150000    3414
150001-250000    2680
60001-80000      2543
40001-60000      2355
80001-100000     2281
>250000          1366
20001-40000      1263
<=20000           415
Unknown            75
dtype: int64

In [ ]:
# Normalize and bucketize screen_size, then one-hot encode
if 'screen_size' in df.columns:
    screen_num = pd.to_numeric(df['screen_size'], errors='coerce')
    screen_bins = [-np.inf, 11, 12.9, 14, 15.6, 16.9, 18.4, np.inf]
    screen_labels = ['<=11"', '11.1-12.9"', '13-14"', '14.1-15.6"', '16-16.9"', '17-18.4"', '>18.4"']
    df['screen_size_class'] = pd.cut(screen_num, bins=screen_bins, labels=screen_labels, right=True)
    df['screen_size_class'] = df['screen_size_class'].astype(object).where(df['screen_size_class'].notna(), 'Unknown')

    screen_size_dummies = pd.get_dummies(df['screen_size_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['screen_size']), screen_size_dummies], axis=1)

    print("\nScreen size classes and counts:")
    print(screen_size_dummies.sum().sort_values(ascending=False))

# One-hot encode screen_resolution, then drop original column
if 'screen_resolution' in df.columns:
    screen_res_dummies = pd.get_dummies(df['screen_resolution'], dummy_na=False)
    screen_res_dummies = screen_res_dummies.rename(columns=lambda c: str(c).strip())
    df = pd.concat([df.drop(columns=['screen_resolution']), screen_res_dummies], axis=1)

    print("\nScreen resolution classes and counts:")
    print(screen_res_dummies.sum().sort_values(ascending=False))

Screen size classes and counts:
13-14"        8372
14.1-15.6"    5668
16-16.9"      1268
17-18.4"       587
11.1-12.9"     386
<=11"          100
>18.4"          11
dtype: int64

Screen resolution classes and counts:
FHD      12929
QHD+      1720
3K         586
WUXGA      278
QHD        233
4K         113
HD         108
HD+         29
5K          28
dtype: int64

In [ ]:
# Normalize and bucketize ram_type, then one-hot encode
if 'ram_type' in df.columns:
    ram_raw = df['ram_type']
    ram_norm = ram_raw.astype(str).str.strip().str.upper()
    ram_norm = ram_norm.where(ram_raw.notna(), np.nan)

    ram_conditions = [
        ram_norm.isna(),
        ram_norm.eq('DDR2'),
        ram_norm.isin(['DDR3', 'DDR3L']),
        ram_norm.isin(['DDR4', 'DDR4X']),
        ram_norm.isin(['DDR5', 'DDR5X']),
        ram_norm.eq('LPDDR3'),
        ram_norm.isin(['LPDDR4', 'LPDDR4X']),
        ram_norm.isin(['LPDDR5', 'LPDDR5X']),
        ram_norm.eq('UNIFIED'),
        ram_norm.eq('DDR')
    ]
    ram_choices = [
        'Unknown',
        'DDR2',
        'DDR3/DDR3L',
        'DDR4/DDR4X',
        'DDR5/DDR5X',
        'LPDDR3',
        'LPDDR4/LPDDR4X',
        'LPDDR5/LPDDR5X',
        'Unified',
        'DDR'
    ]
    df['ram_type_class'] = np.select(ram_conditions, ram_choices, default='Unknown')

    ram_type_dummies = pd.get_dummies(df['ram_type_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['ram_type']), ram_type_dummies], axis=1)

    print("\nRAM type classes and counts:")
    print(ram_type_dummies.sum().sort_values(ascending=False))

# Bucketize cores, then one-hot encode
if 'cores' in df.columns:
    cores_num = pd.to_numeric(df['cores'], errors='coerce')
    cores_bins = [-np.inf, 2, 4, 6, 8, 10, 12, 16, np.inf]
    cores_labels = ['1-2', '3-4', '5-6', '7-8', '9-10', '11-12', '13-16', '>16']
    df['cores_class'] = pd.cut(cores_num, bins=cores_bins, labels=cores_labels, right=True)
    df['cores_class'] = df['cores_class'].astype(object).where(df['cores_class'].notna(), 'Unknown')

    cores_dummies = pd.get_dummies(df['cores_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['cores']), cores_dummies], axis=1)

    print("\nCores classes and counts:")
    print(cores_dummies.sum().sort_values(ascending=False))

# Bucketize cpu_generation, then one-hot encode
if 'cpu_generation' in df.columns:
    gen_num = pd.to_numeric(df['cpu_generation'], errors='coerce')
    gen_bins = [-np.inf, 4, 8, 11, 13, 15, np.inf]
    gen_labels = ['1-4', '5-8', '9-11', '12-13', '14-15', '>15']
    df['cpu_generation_class'] = pd.cut(gen_num, bins=gen_bins, labels=gen_labels, right=True)
    df['cpu_generation_class'] = df['cpu_generation_class'].astype(object).where(df['cpu_generation_class'].notna(), 'Unknown')

    gen_dummies = pd.get_dummies(df['cpu_generation_class'], dummy_na=False)
    df = pd.concat([df.drop(columns=['cpu_generation']), gen_dummies], axis=1)

    print("\nCPU generation classes and counts:")
    print(gen_dummies.sum().sort_values(ascending=False))

RAM type classes and counts:
DDR4/DDR4X        9707
DDR5/DDR5X        3147
LPDDR5/LPDDR5X    1136
DDR3/DDR3L        1040
Unknown            729
LPDDR4/LPDDR4X     419
DDR2                96
LPDDR3              73
DDR                 26
Unified             19
dtype: int64

Cores classes and counts:
3-4        6527
1-2        5465
5-6        2042
7-8        1397
Unknown     793
9-10         81
11-12        74
13-16        13
dtype: int64

CPU generation classes and counts:
5-8        4524
9-11       3716
12-13      3700
1-4        2267
Unknown    1410
14-15       775
dtype: int64

In [ ]:
import re

def _norm_text(value):
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return None
    text = str(value).strip()
    return text if text else None

def extract_dedicated_gpu(gpu_name):
    text = _norm_text(gpu_name)
    if text is None:
        return 'Unknown'
    upper = text.upper()

    # Dedicated checks
    if any(token in upper for token in ['GEFORCE', 'GTX', 'RTX', 'QUADRO', 'PRO W']):
        return 'Dedicated'
    if re.search(r'\bMX\s*\d{3,4}\b', upper):
        return 'Dedicated'
    if re.search(r'\bRADEON\s+PRO\b', upper):
        return 'Dedicated'
    if re.search(r'\bRADEON\s+\d{3,4}M\b', upper):
        return 'Dedicated'

    # Integrated checks
    if any(token in upper for token in ['UHD', 'HD GRAPHICS', 'IRIS', 'ARC']):
        return 'Integrated'
    if 'RADEON GRAPHICS' in upper and not re.search(r'\b\d{3,4}M\b', upper):
        return 'Integrated'
    if 'VEGA' in upper:
        return 'Integrated'
    if 'ADRENO' in upper:
        return 'Integrated'
    if 'APPLE' in upper or re.search(r'\bM[1-4]\b', upper):
        return 'Integrated'

    return 'Unknown'

def extract_gpu_family(gpu_name):
    text = _norm_text(gpu_name)
    if text is None:
        return 'Unknown'
    upper = text.upper()

    # NVIDIA
    if 'RTX' in upper:
        rtx_match = re.search(r'RTX\s*([2-5]\d{2,3})', upper)
        if rtx_match:
            model = int(rtx_match.group(1))
            if model >= 4000:
                return 'NVIDIA_RTX_40_50'
            if 2000 <= model <= 3999:
                return 'NVIDIA_RTX_20_30'
        if re.search(r'RTX\s*4\d{2}', upper) or re.search(r'RTX\s*5\d{2}', upper):
            return 'NVIDIA_RTX_40_50'
        if re.search(r'RTX\s*2\d{2}', upper) or re.search(r'RTX\s*3\d{2}', upper):
            return 'NVIDIA_RTX_20_30'
    if 'GTX' in upper:
        return 'NVIDIA_GTX'
    if re.search(r'\bMX\s*\d{3,4}\b', upper):
        return 'NVIDIA_MX'
    if any(token in upper for token in ['NVIDIA', 'GEFORCE', 'QUADRO', 'TESLA']):
        return 'NVIDIA_Legacy'

    # AMD
    if 'RADEON PRO' in upper:
        return 'AMD_Radeon_Pro'
    if re.search(r'\b([6-8]\d{2})M\b', upper):
        return 'AMD_Radeon_Mobile'
    if 'RADEON GRAPHICS' in upper or 'VEGA' in upper:
        return 'AMD_Radeon_Integrated'
    if 'RADEON' in upper:
        return 'AMD_Radeon_Integrated'

    # Intel
    if 'ARC' in upper:
        return 'Intel_Arc'
    if 'IRIS' in upper:
        return 'Intel_Iris'
    if 'UHD' in upper or 'HD GRAPHICS' in upper:
        return 'Intel_Integrated'

    # Apple
    if 'APPLE' in upper or re.search(r'\bM[1-4]\b', upper):
        return 'Apple_GPU'

    # Qualcomm
    if 'ADRENO' in upper:
        return 'Qualcomm_Adreno'

    return 'Unknown'

def _apple_gpu_core_count(upper):
    match = re.search(r'(\d{1,2})\s*-?\s*CORE', upper)
    if match:
        return int(match.group(1))
    return None

def extract_gpu_tier(gpu_name):
    text = _norm_text(gpu_name)
    if text is None:
        return 'Unknown'
    upper = text.upper()

    # Legacy checks
    if re.search(r'\bGMA\b', upper) or re.search(r'\bRADEON\s+X\d{3,4}\b', upper):
        return 'Legacy'
    if re.search(r'\bGEFORCE\s+[6-8]\d{3}\b', upper):
        return 'Legacy'
    if 'QUADRO' in upper and re.search(r'\b[1-3]\d{3}\b', upper):
        return 'Legacy'

    # Apple GPU tiers by core count
    if 'APPLE' in upper or re.search(r'\bM[1-4]\b', upper):
        cores = _apple_gpu_core_count(upper)
        if cores is not None:
            if cores >= 38:
                return 'High_End'
            if 14 <= cores <= 37:
                return 'Mid_Range'
            if cores < 14:
                return 'Entry_Level'

    # NVIDIA RTX tiers
    rtx_match = re.search(r'RTX\s*([2-5]\d{2,3})', upper)
    if rtx_match:
        model = int(rtx_match.group(1))
        if model in [5090, 5080, 5070, 4090, 4080, 4070, 3090, 3080, 3070]:
            return 'High_End'
        if model in [5060, 4060, 3060, 2060, 4050, 3050, 2050]:
            return 'Mid_Range'
        return 'Entry_Level'

    # NVIDIA GTX tiers
    gtx_match = re.search(r'GTX\s*(\d{3,4})', upper)
    if gtx_match:
        model = int(gtx_match.group(1))
        if model in [1080, 1070]:
            return 'High_End'
        if model in [1660, 1650, 1060, 960, 970]:
            return 'Mid_Range'
        if model <= 980 and model not in [960, 970]:
            return 'Entry_Level'
        return 'Entry_Level'

    # NVIDIA GT / MX tiers
    if re.search(r'\bGT\s*\d{2,3}\b', upper):
        return 'Entry_Level'
    if re.search(r'\bMX\s*\d{3,4}\b', upper):
        return 'Entry_Level'

    # AMD tiers
    if re.search(r'\b(890|780)M\b', upper):
        return 'High_End'
    if re.search(r'\b(740|680|660|610)M\b', upper):
        return 'Mid_Range'
    if re.search(r'RADEON\s+PRO\s+W(6300|5500|5700)\b', upper):
        return 'High_End'
    if 'RADEON GRAPHICS' in upper or 'VEGA' in upper:
        return 'Entry_Level'

    # Intel tiers
    if 'ARC' in upper:
        return 'Mid_Range'
    if any(token in upper for token in ['UHD', 'HD GRAPHICS', 'IRIS']):
        return 'Entry_Level'

    # Qualcomm
    if 'ADRENO' in upper:
        return 'Entry_Level'

    return 'Unknown'

def _intel_generation(upper):
    match = re.search(r'\bI[3579]-\s*(\d{3,5})', upper)
    if not match:
        return None
    digits = match.group(1)
    if len(digits) >= 4:
        return int(digits[:2])
    return int(digits[0])

def _amd_ryzen_series(upper):
    match = re.search(r'RYZEN\s*[3579]\s*(\d{4,5})', upper)
    if not match:
        return None
    digits = match.group(1)
    if len(digits) >= 4:
        return int(digits[0]) * 1000
    return int(digits)

def extract_cpu_tier(mapped_cpu_name):
    text = _norm_text(mapped_cpu_name)
    if text is None:
        return 'Unknown'
    upper = text.upper()

    # Legacy CPUs
    if any(token in upper for token in ['ATOM', 'PENTIUM M', 'CORE 2 DUO', 'CORE DUO', 'SEMPRON', 'E1', 'E2', 'SNAPDRAGON', 'VIA']):
        return 'Legacy'

    # High-end
    if any(token in upper for token in ['I9', 'XEON', 'ULTRA 9', 'RYZEN 9']):
        return 'High_End'
    if re.search(r'\bI7-\d+.*\b(HX|HK)\b', upper):
        return 'High_End'
    if re.search(r'\bM[1-4]\s*(PRO|MAX|ULTRA)\b', upper):
        return 'High_End'

    # Mid-range
    if re.search(r'\bI7-\d+.*\b(H|P)\b', upper):
        return 'Mid_Range'
    if re.search(r'\bI5-\d+.*\b(H|HX|P)\b', upper):
        return 'Mid_Range'
    if any(token in upper for token in ['ULTRA 7', 'ULTRA 5']):
        return 'Mid_Range'
    if 'RYZEN 7' in upper:
        return 'Mid_Range'
    if 'RYZEN 5' in upper:
        amd_series = _amd_ryzen_series(upper)
        if amd_series is not None and amd_series >= 5000:
            return 'Mid_Range'
        return 'Entry_Level'
    if re.search(r'\bM[1-4]\b', upper) and not re.search(r'\bM[1-4]\s*(PRO|MAX|ULTRA)\b', upper):
        return 'Mid_Range'

    # Entry-level
    if 'I3' in upper:
        return 'Entry_Level'
    if re.search(r'\bI5-\d+.*\b(U|G)\b', upper):
        return 'Entry_Level'
    if any(token in upper for token in ['PENTIUM', 'CELERON', 'CORE M', 'RYZEN 3', 'ATHLON']):
        return 'Entry_Level'
    if re.search(r'\bA(6|8|10|12)\b', upper):
        return 'Entry_Level'
    intel_gen = _intel_generation(upper)
    if intel_gen is not None and intel_gen <= 4:
        return 'Entry_Level'

    return 'Unknown'

In [ ]:
# Create categorical columns using extraction functions
if 'gpu_name' in df.columns:
    df['dedicated_gpu'] = df['gpu_name'].apply(extract_dedicated_gpu)
    df['gpu_family'] = df['gpu_name'].apply(extract_gpu_family)
    df['gpu_tier'] = df['gpu_name'].apply(extract_gpu_tier)

if 'mapped_cpu_name' in df.columns:
    df['cpu_tier'] = df['mapped_cpu_name'].apply(extract_cpu_tier)

# One-hot encode new categorical columns and drop originals
columns_to_encode = ['dedicated_gpu', 'gpu_family', 'gpu_tier', 'cpu_tier']
for col in columns_to_encode:
    if col in df.columns:
        dummies = pd.get_dummies(df[col], dummy_na=False)
        dummies = dummies.rename(columns=lambda c: f"{col}_{str(c).strip()}")
        df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

# Drop old source columns after encoding
columns_to_drop = ['gpu_name', 'mapped_cpu_name']
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("\nGPU/CPU derived columns added and one-hot encoded.")
print("\nCurrent column count:", len(df.columns))

GPU/CPU derived columns added and one-hot encoded.

Current column count: 160

In [ ]:
# display the columns of df to verify the changes and the number of columns
print("\nFinal dataset columns after all transformations:")
print(df.columns.to_list())
print(f"\nTotal number of columns: {len(df.columns)}")
print(df.shape)

# allow to print many rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# list the type of each column
print("\nColumn data types:")
print(df.dtypes)

Final dataset columns after all transformations:
['id', 'cpu_family_type', 'Bon_état', 'jamais_utilisé', 'moyen', 'AERO', 'ALIENWARE', 'ASPIRE', 'BLADE', 'COMPAQ', 'DYNABOOK', 'ELITEBOOK', 'ENVY', 'GALAXY', 'GF', 'IDEAPAD', 'IMAC', 'INSPIRON', 'KATANA', 'LATITUDE', 'LEGION', 'MAC', 'MACBOOK', 'NITRO', 'OMEN', 'OPTIPLEX', 'PAVILION', 'PRECISION', 'PREDATOR', 'PROBOOK', 'ROG', 'SPECTRE', 'SPIN', 'STEALTH', 'STRIX', 'SURFACE', 'SWIFT', 'SWORD', 'THINKBOOK', 'THINKPAD', 'TRANSFORMER', 'TRAVELMATE', 'TUF', 'VECTOR', 'VICTUS', 'VIVOBOOK', 'VOSTRO', 'XPS', 'YOGA', 'ZBOOK', 'ZENBOOK', 'ram_size_class', '12-18GB', '2-4GB', '20-30GB', '32-64GB', '6-10GB', '<2GB', '>64GB', 'Unknown', 'ssd_size_class', '1.1-2TB', '129-256GB', '2.1-4TB', '257-512GB', '4.1-8TB', '513-1024GB', '<=128GB', '>8TB', 'Unknown', 'hdd_size_class', '1.1-2TB', '129-256GB', '2.1-4TB', '257-512GB', '513-1024GB', '<=128GB', '>8TB', 'Unknown', 'price_class', '100001-150000', '150001-250000', '20001-40000', '40001-60000', '60001-80000', '80001-100000', '<=20000', '>250000', 'Unknown', 'screen_size_class', '11.1-12.9"', '13-14"', '14.1-15.6"', '16-16.9"', '17-18.4"', '<=11"', '>18.4"', '3K', '4K', '5K', 'FHD', 'HD', 'HD+', 'QHD', 'QHD+', 'WUXGA', 'ram_type_class', 'DDR', 'DDR2', 'DDR3/DDR3L', 'DDR4/DDR4X', 'DDR5/DDR5X', 'LPDDR3', 'LPDDR4/LPDDR4X', 'LPDDR5/LPDDR5X', 'Unified', 'Unknown', 'cores_class', '1-2', '11-12', '13-16', '3-4', '5-6', '7-8', '9-10', 'Unknown', 'cpu_generation_class', '1-4', '12-13', '14-15', '5-8', '9-11', 'Unknown', 'dedicated_gpu_Dedicated', 'dedicated_gpu_Integrated', 'dedicated_gpu_Unknown', 'gpu_family_AMD_Radeon_Integrated', 'gpu_family_AMD_Radeon_Mobile', 'gpu_family_AMD_Radeon_Pro', 'gpu_family_Apple_GPU', 'gpu_family_Intel_Arc', 'gpu_family_Intel_Integrated', 'gpu_family_Intel_Iris', 'gpu_family_NVIDIA_GTX', 'gpu_family_NVIDIA_Legacy', 'gpu_family_NVIDIA_MX', 'gpu_family_NVIDIA_RTX_20_30', 'gpu_family_NVIDIA_RTX_40_50', 'gpu_family_Qualcomm_Adreno', 'gpu_family_Unknown', 'gpu_tier_Entry_Level', 'gpu_tier_High_End', 'gpu_tier_Legacy', 'gpu_tier_Mid_Range', 'gpu_tier_Unknown', 'cpu_tier_Entry_Level', 'cpu_tier_High_End', 'cpu_tier_Legacy', 'cpu_tier_Mid_Range', 'cpu_tier_Unknown']

Total number of columns: 160
(16392, 160)

Column data types:
id                                   int64
cpu_family_type                     object
Bon_état                              bool
jamais_utilisé                        bool
moyen                                 bool
AERO                                  bool
ALIENWARE                             bool
ASPIRE                                bool
BLADE                                 bool
COMPAQ                                bool
DYNABOOK                              bool
ELITEBOOK                             bool
ENVY                                  bool
GALAXY                                bool
GF                                    bool
IDEAPAD                               bool
IMAC                                  bool
INSPIRON                              bool
KATANA                                bool
LATITUDE                              bool
LEGION                                bool
MAC                                   bool
MACBOOK                               bool
NITRO                                 bool
OMEN                                  bool
OPTIPLEX                              bool
PAVILION                              bool
PRECISION                             bool
PREDATOR                              bool
PROBOOK                               bool
ROG                                   bool
SPECTRE                               bool
SPIN                                  bool
STEALTH                               bool
STRIX                                 bool
SURFACE                               bool
SWIFT                                 bool
SWORD                                 bool
THINKBOOK                             bool
THINKPAD                              bool
TRANSFORMER                           bool
TRAVELMATE                            bool
TUF                                   bool
VECTOR                                bool
VICTUS                                bool
VIVOBOOK                              bool
VOSTRO                                bool
XPS                                   bool
YOGA                                  bool
ZBOOK                                 bool
ZENBOOK                               bool
ram_size_class                      object
12-18GB                               bool
2-4GB                                 bool
20-30GB                               bool
32-64GB                               bool
6-10GB                                bool
<2GB                                  bool
>64GB                                 bool
Unknown                               bool
ssd_size_class                      object
1.1-2TB                               bool
129-256GB                             bool
2.1-4TB                               bool
257-512GB                             bool
4.1-8TB                               bool
513-1024GB                            bool
<=128GB                               bool
>8TB                                  bool
Unknown                               bool
hdd_size_class                      object
1.1-2TB                               bool
129-256GB                             bool
2.1-4TB                               bool
257-512GB                             bool
513-1024GB                            bool
<=128GB                               bool
>8TB                                  bool
Unknown                               bool
price_class                         object
100001-150000                         bool
150001-250000                         bool
20001-40000                           bool
40001-60000                           bool
60001-80000                           bool
80001-100000                          bool
<=20000                               bool
>250000                               bool
Unknown                               bool
screen_size_class                   object
11.1-12.9"                            bool
13-14"                                bool
14.1-15.6"                            bool
16-16.9"                              bool
17-18.4"                              bool
<=11"                                 bool
>18.4"                                bool
3K                                    bool
4K                                    bool
5K                                    bool
FHD                                   bool
HD                                    bool
HD+                                   bool
QHD                                   bool
QHD+                                  bool
WUXGA                                 bool
ram_type_class                      object
DDR                                   bool
DDR2                                  bool
DDR3/DDR3L                            bool
DDR4/DDR4X                            bool
DDR5/DDR5X                            bool
LPDDR3                                bool
LPDDR4/LPDDR4X                        bool
LPDDR5/LPDDR5X                        bool
Unified                               bool
Unknown                               bool
cores_class                         object
1-2                                   bool
11-12                                 bool
13-16                                 bool
3-4                                   bool
5-6                                   bool
7-8                                   bool
9-10                                  bool
Unknown                               bool
cpu_generation_class                object
1-4                                   bool
12-13                                 bool
14-15                                 bool
5-8                                   bool
9-11                                  bool
Unknown                               bool
dedicated_gpu_Dedicated               bool
dedicated_gpu_Integrated              bool
dedicated_gpu_Unknown                 bool
gpu_family_AMD_Radeon_Integrated      bool
gpu_family_AMD_Radeon_Mobile          bool
gpu_family_AMD_Radeon_Pro             bool
gpu_family_Apple_GPU                  bool
gpu_family_Intel_Arc                  bool
gpu_family_Intel_Integrated           bool
gpu_family_Intel_Iris                 bool
gpu_family_NVIDIA_GTX                 bool
gpu_family_NVIDIA_Legacy              bool
gpu_family_NVIDIA_MX                  bool
gpu_family_NVIDIA_RTX_20_30           bool
gpu_family_NVIDIA_RTX_40_50           bool
gpu_family_Qualcomm_Adreno            bool
gpu_family_Unknown                    bool
gpu_tier_Entry_Level                  bool
gpu_tier_High_End                     bool
gpu_tier_Legacy                       bool
gpu_tier_Mid_Range                    bool
gpu_tier_Unknown                      bool
cpu_tier_Entry_Level                  bool
cpu_tier_High_End                     bool
cpu_tier_Legacy                       bool
cpu_tier_Mid_Range                    bool
cpu_tier_Unknown                      bool
dtype: object

In [ ]:
# remove columns 'Unknown'
columns_to_remove = [col for col in df.columns if 'Unknown' in col]
df.drop(columns=columns_to_remove, inplace=True, errors='ignore')   

# display all columns named 'Uknown' to check
print("\nColumns containing 'Unknown':")
unknown_columns = [col for col in df.columns if 'Unknown' in col]
print(unknown_columns)

Columns containing 'Unknown':
[]

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth

def _get_model_name_columns(df):
    if 'model_name_dummies' in globals():
        return [c for c in model_name_dummies.columns if c in df.columns]
    return []

def _get_gen_columns(df):
    if 'gen_dummies' in globals():
        return [c for c in gen_dummies.columns if c in df.columns]
    return []

def _is_binary_series(series):
    values = set(series.dropna().unique())
    return values <= {0, 1}

def build_experiment_df(df, drop_prefixes=None, drop_columns=None):
    data = df.copy()
    drop_cols = set()
    if drop_prefixes:
        drop_cols.update([c for c in data.columns if any(c.startswith(p) for p in drop_prefixes)])
    if drop_columns:
        drop_cols.update([c for c in drop_columns if c in data.columns])
    data = data.drop(columns=list(drop_cols), errors='ignore')

    # Keep only binary columns (handle duplicate column names)
    binary_idx = []
    for idx, col in enumerate(data.columns):
        series = data.iloc[:, idx]
        if _is_binary_series(series):
            binary_idx.append(idx)
    return data.iloc[:, binary_idx]

def run_rules_apriori(data, min_support=0.02, min_confidence=0.5, min_lift=1.0, max_len=None, top_n=20):
    frequent = apriori(data, min_support=min_support, use_colnames=True, max_len=max_len, low_memory=True)
    rules = association_rules(frequent, num_itemsets=len(data), metric='confidence', min_threshold=min_confidence)
    rules = rules[rules['lift'] >= min_lift]
    rules = rules.sort_values(['lift', 'confidence'], ascending=False)
    return frequent, rules.head(top_n)

def run_rules_fpgrowth(data, min_support=0.02, min_confidence=0.5, min_lift=1.0, max_len=None, top_n=20):
    frequent = fpgrowth(data, min_support=min_support, use_colnames=True, max_len=max_len)
    rules = association_rules(frequent, num_itemsets=len(data), metric='confidence', min_threshold=min_confidence)
    rules = rules[rules['lift'] >= min_lift]
    rules = rules.sort_values(['lift', 'confidence'], ascending=False)
    return frequent, rules.head(top_n)

# Build experiment datasets
model_name_cols = _get_model_name_columns(df)
gen_cols = _get_gen_columns(df)

exp_1_1 = build_experiment_df(
    df,
    drop_prefixes=['cpu_fam_', 'gpu_family_'],
    drop_columns=['cpu_generation_class'] + gen_cols
)

exp_1_2 = build_experiment_df(
    df,
    drop_prefixes=['cpu_fam_', 'gpu_family_'],
    drop_columns=['cpu_generation_class'] + gen_cols + model_name_cols
)

exp_2_1 = build_experiment_df(
    df,
    drop_prefixes=['cpu_tier_', 'gpu_tier_'],
    drop_columns=['cpu_generation_class']
)

exp_2_2 = build_experiment_df(
    df,
    drop_prefixes=['cpu_tier_', 'gpu_tier_'],
    drop_columns=['cpu_generation_class'] + model_name_cols
 )

print("Experiment datasets ready:")
print("exp_1_1:", exp_1_1.shape)
print("exp_1_2:", exp_1_2.shape)
print("exp_2_1:", exp_2_1.shape)
print("exp_2_2:", exp_2_2.shape)

Experiment datasets ready:
exp_1_1: (16392, 121)
exp_1_2: (16392, 75)
exp_2_1: (16392, 131)
exp_2_2: (16392, 85)

In [ ]:
# Example run (Apriori)
# experiment 1-1
frequent_1_1, rules_1_1 = run_rules_apriori(exp_1_1, min_support=0.05, min_confidence=0.6, min_lift=1.1)
print("\nTop rules - Experiment 1-1 (Apriori)")
display(rules_1_1)

Top rules - Experiment 1-1 (Apriori)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
331,"(QHD+, 13-14"")",(MACBOOK),0.071437,0.101452,0.068814,0.963279,9.494933,1.0,0.061567,24.469763,0.963511,0.661196,0.959133,0.820786
332,(MACBOOK),"(QHD+, 13-14"")",0.101452,0.071437,0.068814,0.678292,9.494933,1.0,0.061567,2.886355,0.995696,0.661196,0.653542,0.820786
1636,"(dedicated_gpu_Integrated, QHD+, 13-14"")",(MACBOOK),0.053624,0.101452,0.051306,0.956769,9.430763,1.0,0.045865,20.784836,0.944618,0.494415,0.951888,0.731241
336,"(dedicated_gpu_Integrated, QHD+)",(MACBOOK),0.073389,0.101452,0.070095,0.955112,9.414431,1.0,0.062650,20.017654,0.964569,0.669190,0.950044,0.823016
340,(MACBOOK),"(dedicated_gpu_Integrated, QHD+)",0.101452,0.073389,0.070095,0.690920,9.414431,1.0,0.062650,2.997964,0.994694,0.669190,0.666440,0.823016
1640,"(dedicated_gpu_Integrated, QHD+)","(MACBOOK, 13-14"")",0.073389,0.074366,0.051306,0.699086,9.400666,1.0,0.045848,3.076073,0.964401,0.531942,0.674910,0.694498
1643,"(MACBOOK, 13-14"")","(dedicated_gpu_Integrated, QHD+)",0.074366,0.073389,0.051306,0.689910,9.400666,1.0,0.045848,2.988196,0.965418,0.531942,0.665350,0.694498
1642,"(QHD+, 13-14"")","(dedicated_gpu_Integrated, MACBOOK)",0.071437,0.076745,0.051306,0.718190,9.358159,1.0,0.045823,3.276157,0.961854,0.529597,0.694764,0.693356
1641,"(dedicated_gpu_Integrated, MACBOOK)","(QHD+, 13-14"")",0.076745,0.071437,0.051306,0.668521,9.358159,1.0,0.045823,2.801276,0.967383,0.529597,0.643020,0.693356
330,"(MACBOOK, 13-14"")",(QHD+),0.074366,0.104929,0.068814,0.925349,8.818788,1.0,0.061011,11.990014,0.957836,0.622860,0.916597,0.790581
333,(QHD+),"(MACBOOK, 13-14"")",0.104929,0.074366,0.068814,0.655814,8.818788,1.0,0.061011,2.689343,0.990543,0.622860,0.628162,0.790581
1638,"(dedicated_gpu_Integrated, 13-14"", MACBOOK)",(QHD+),0.055515,0.104929,0.051306,0.924176,8.807611,1.0,0.045480,11.804556,0.938566,0.470095,0.915287,0.706565
1031,(LPDDR5/LPDDR5X),"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.069302,0.084553,0.051245,0.739437,8.745198,1.0,0.045385,3.513335,0.951599,0.499405,0.715370,0.672749
1029,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",(LPDDR5/LPDDR5X),0.084553,0.069302,0.051245,0.606061,8.745198,1.0,0.045385,2.362541,0.967453,0.499405,0.576727,0.672749
19,(MACBOOK),(QHD+),0.101452,0.104929,0.092911,0.915815,8.727928,1.0,0.082266,10.632162,0.985396,0.818817,0.905946,0.900640
20,(QHD+),(MACBOOK),0.104929,0.101452,0.092911,0.885465,8.727928,1.0,0.082266,7.845191,0.989224,0.818817,0.872533,0.900640
339,(QHD+),"(dedicated_gpu_Integrated, MACBOOK)",0.104929,0.076745,0.070095,0.668023,8.704481,1.0,0.062042,2.781084,0.988879,0.628212,0.640428,0.790689
337,"(dedicated_gpu_Integrated, MACBOOK)",(QHD+),0.076745,0.104929,0.070095,0.913355,8.704481,1.0,0.062042,10.330266,0.958691,0.628212,0.903197,0.790689
3282,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)","(cpu_tier_Mid_Range, 13-14"")",0.084553,0.076623,0.051672,0.611111,7.975584,1.0,0.045193,2.374399,0.955400,0.471866,0.578841,0.642737
3283,"(cpu_tier_Mid_Range, 13-14"")","(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.076623,0.084553,0.051672,0.674363,7.975584,1.0,0.045193,2.811249,0.947194,0.471866,0.644286,0.642737

### Experiment 1-1: Apriori Results (Tier-Based, MacBook-Focused)

**Strongest Associations (Lift > 8):**

| Antecedent | Consequent | Conf. | Lift |
|------------|------------|-------|------|
| QHD+, 13-14" | MacBook | **96.3%** | 9.49 |
| Integrated GPU, QHD+ | MacBook | 95.5% | 9.41 |
| MacBook, 13-14" | QHD+ | 92.5% | 8.82 |
| LPDDR5 | Integrated GPU, Mid-Range | 73.9% | 8.75 |

**Key Insight:** Apple dominates the premium compact display segment. 96% of laptops with QHD+ and 13-14" screens are MacBooks.

In [ ]:
# Example run (Apriori)
# experiment 1-2
frequent_1_2, rules_1_2 = run_rules_apriori(exp_1_2, min_support=0.05, min_confidence=0.6, min_lift=1.1)
print("\nTop rules - Experiment 1-2 (Apriori)")
display(rules_1_2)

Top rules - Experiment 1-2 (Apriori)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
846,(LPDDR5/LPDDR5X),"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.069302,0.084553,0.051245,0.739437,8.745198,1.0,0.045385,3.513335,0.951599,0.499405,0.715370,0.672749
844,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",(LPDDR5/LPDDR5X),0.084553,0.069302,0.051245,0.606061,8.745198,1.0,0.045385,2.362541,0.967453,0.499405,0.576727,0.672749
2684,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)","(cpu_tier_Mid_Range, 13-14"")",0.084553,0.076623,0.051672,0.611111,7.975584,1.0,0.045193,2.374399,0.955400,0.471866,0.578841,0.642737
2685,"(cpu_tier_Mid_Range, 13-14"")","(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.076623,0.084553,0.051672,0.674363,7.975584,1.0,0.045193,2.811249,0.947194,0.471866,0.644286,0.642737
2686,"(gpu_tier_Mid_Range, 13-14"")","(dedicated_gpu_Integrated, cpu_tier_Mid_Range)",0.072840,0.105722,0.051672,0.709380,6.709845,1.0,0.043971,3.077140,0.917820,0.407212,0.675023,0.599064
2682,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range,...",(cpu_tier_Mid_Range),0.060212,0.145620,0.051672,0.858156,5.893127,1.0,0.042903,6.023380,0.883509,0.335180,0.833980,0.606497
863,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",(cpu_tier_Mid_Range),0.084553,0.145620,0.069790,0.825397,5.668163,1.0,0.057477,4.893268,0.899644,0.435146,0.795638,0.652330
2246,"(dedicated_gpu_Dedicated, 257-512GB)","(FHD, gpu_tier_Mid_Range)",0.103038,0.117374,0.063995,0.621078,5.291426,1.0,0.051901,2.329304,0.904180,0.409126,0.570687,0.583148
724,"(gpu_tier_Mid_Range, 13-14"")",(cpu_tier_Mid_Range),0.072840,0.145620,0.056064,0.769682,5.285556,1.0,0.045457,3.709563,0.874504,0.345229,0.730426,0.577342
2721,"(gpu_tier_Mid_Range, 14.1-15.6"")","(dedicated_gpu_Dedicated, FHD)",0.075098,0.163372,0.060273,0.802600,4.912700,1.0,0.048004,4.238225,0.861114,0.338240,0.764052,0.585766
2720,"(FHD, gpu_tier_Mid_Range, 14.1-15.6"")",(dedicated_gpu_Dedicated),0.064239,0.197352,0.060273,0.938272,4.754296,1.0,0.047596,13.002892,0.843873,0.299394,0.923094,0.621841
753,"(gpu_tier_Mid_Range, 14.1-15.6"")",(dedicated_gpu_Dedicated),0.075098,0.197352,0.065642,0.874086,4.429063,1.0,0.050821,6.374576,0.837081,0.317404,0.843127,0.603349
1481,"(FHD, gpu_tier_Mid_Range, 12-18GB)",(dedicated_gpu_Dedicated),0.084248,0.197352,0.069058,0.819696,4.153464,1.0,0.052431,4.451632,0.829086,0.324914,0.775363,0.584809
843,"(dedicated_gpu_Integrated, LPDDR5/LPDDR5X)",(gpu_tier_Mid_Range),0.063324,0.196437,0.051245,0.809249,4.119628,1.0,0.038805,4.212617,0.808454,0.245758,0.762618,0.535059
2245,"(FHD, 257-512GB, gpu_tier_Mid_Range)",(dedicated_gpu_Dedicated),0.079307,0.197352,0.063995,0.806923,4.088743,1.0,0.048343,4.157139,0.820497,0.300918,0.759450,0.565594
800,"(FHD, gpu_tier_Mid_Range)",(dedicated_gpu_Dedicated),0.117374,0.197352,0.094314,0.803534,4.071572,1.0,0.071150,4.085434,0.854716,0.427899,0.755228,0.640716
99,(LPDDR5/LPDDR5X),(gpu_tier_Mid_Range),0.069302,0.196437,0.054600,0.787852,4.010706,1.0,0.040986,3.787748,0.806564,0.258596,0.735991,0.532901
840,"(DDR5/DDR5X, gpu_tier_Mid_Range)",(dedicated_gpu_Dedicated),0.074610,0.197352,0.057589,0.771872,3.911139,1.0,0.042865,3.518416,0.804331,0.268640,0.715781,0.531840
2681,"(dedicated_gpu_Integrated, cpu_tier_Mid_Range,...",(gpu_tier_Mid_Range),0.069668,0.196437,0.051672,0.741681,3.775664,1.0,0.037986,3.110741,0.790198,0.240967,0.678533,0.502362
723,"(cpu_tier_Mid_Range, 13-14"")",(gpu_tier_Mid_Range),0.076623,0.196437,0.056064,0.731688,3.724791,1.0,0.041012,2.994881,0.792232,0.258364,0.666097,0.508546

### Experiment 1-2: Apriori Results Gaming/Creator Segment Patterns

**Mid-Range GPU Associations (Lift 4-8):**

| Antecedent | Consequent | Conf. | Lift | Insight |
|------------|------------|-------|------|---------|
| LPDDR5 | Integrated GPU, Mid-Tier | 73.9% | 8.75 | Ultrabook standard |
| Mid-CPU, 13-14" | Integrated GPU, Mid-GPU | 67.4% | 7.98 | Compact efficiency |
| Integrated GPU, Mid-GPU | Mid-CPU | 82.5% | 5.67 | Tier correlation |
| Dedicated GPU, 257-512GB | FHD, Mid-GPU | 62.1% | 5.29 | Gaming config |

**Key Finding:** Gaming laptops standardize on FHD displays (not 4K), 256-512GB SSD, and mid-range dedicated GPUs.

In [ ]:
# Example run (Apriori)
# experiment 2-1
frequent_2_1, rules_2_1 = run_rules_apriori(exp_2_1, min_support=0.05, min_confidence=0.5, min_lift=1.05)
print("\nTop rules - Experiment 2-1 (Apriori)")
display(rules_2_1)

Top rules - Experiment 2-1 (Apriori)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
6561,"(1-4, QHD+, dedicated_gpu_Integrated)","(MACBOOK, gpu_family_Apple_GPU)",0.060273,0.058992,0.054051,0.896761,15.201353,1.0,0.050495,9.114860,0.994136,0.828812,0.890289,0.906498
6579,"(MACBOOK, gpu_family_Apple_GPU)","(1-4, QHD+, dedicated_gpu_Integrated)",0.058992,0.060273,0.054051,0.916236,15.201353,1.0,0.050495,11.218713,0.992783,0.828812,0.910863,0.906498
6578,"(gpu_family_Apple_GPU, QHD+)","(1-4, dedicated_gpu_Integrated, MACBOOK)",0.054112,0.065947,0.054051,0.998873,15.146642,1.0,0.050482,828.505185,0.987409,0.818854,0.998793,0.909242
6562,"(1-4, dedicated_gpu_Integrated, MACBOOK)","(gpu_family_Apple_GPU, QHD+)",0.065947,0.054112,0.054051,0.819611,15.146642,1.0,0.050482,5.243616,0.999920,0.818854,0.809292,0.909242
2300,"(MACBOOK, gpu_family_Apple_GPU)","(1-4, QHD+)",0.058992,0.060578,0.054051,0.916236,15.124811,1.0,0.050477,11.215071,0.992429,0.824953,0.910834,0.904241
6569,"(dedicated_gpu_Integrated, gpu_family_Apple_GP...","(1-4, QHD+)",0.058992,0.060578,0.054051,0.916236,15.124811,1.0,0.050477,11.215071,0.992429,0.824953,0.910834,0.904241
2305,"(1-4, QHD+)","(MACBOOK, gpu_family_Apple_GPU)",0.060578,0.058992,0.054051,0.892246,15.124811,1.0,0.050477,8.732904,0.994105,0.824953,0.885491,0.904241
6571,"(1-4, QHD+)","(dedicated_gpu_Integrated, gpu_family_Apple_GP...",0.060578,0.058992,0.054051,0.892246,15.124811,1.0,0.050477,8.732904,0.994105,0.824953,0.885491,0.904241
2302,"(MACBOOK, 1-4)","(gpu_family_Apple_GPU, QHD+)",0.066252,0.054112,0.054051,0.815838,15.076906,1.0,0.050466,5.136173,0.999920,0.815087,0.805303,0.907355
6572,"(1-4, MACBOOK)","(dedicated_gpu_Integrated, gpu_family_Apple_GP...",0.066252,0.054112,0.054051,0.815838,15.076906,1.0,0.050466,5.136173,0.999920,0.815087,0.805303,0.907355
2303,"(gpu_family_Apple_GPU, QHD+)","(MACBOOK, 1-4)",0.054112,0.066252,0.054051,0.998873,15.076906,1.0,0.050466,828.234627,0.987086,0.815087,0.998793,0.907355
6568,"(dedicated_gpu_Integrated, gpu_family_Apple_GP...","(1-4, MACBOOK)",0.054112,0.066252,0.054051,0.998873,15.076906,1.0,0.050466,828.234627,0.987086,0.815087,0.998793,0.907355
6582,(gpu_family_Apple_GPU),"(1-4, QHD+, dedicated_gpu_Integrated, MACBOOK)",0.061859,0.060151,0.054051,0.873767,14.526159,1.0,0.050330,7.445364,0.992558,0.795332,0.865688,0.886174
6556,"(1-4, QHD+, dedicated_gpu_Integrated, MACBOOK)",(gpu_family_Apple_GPU),0.060151,0.061859,0.054051,0.898580,14.526159,1.0,0.050330,9.250066,0.990754,0.795332,0.891893,0.886174
5426,"(dedicated_gpu_Integrated, 1-4, QHD+)",(gpu_family_Apple_GPU),0.060273,0.061859,0.054112,0.897773,14.513116,1.0,0.050383,9.177058,0.990817,0.795516,0.891033,0.886263
5433,(gpu_family_Apple_GPU),"(dedicated_gpu_Integrated, 1-4, QHD+)",0.061859,0.060273,0.054112,0.874753,14.513116,1.0,0.050383,7.503015,0.992492,0.795516,0.866720,0.886263
2332,(gpu_family_Apple_GPU),"(MACBOOK, 1-4, dedicated_gpu_Integrated)",0.061859,0.065947,0.058992,0.953649,14.460882,1.0,0.054913,20.151701,0.992227,0.857270,0.950376,0.924096
2324,"(MACBOOK, 1-4, dedicated_gpu_Integrated)",(gpu_family_Apple_GPU),0.065947,0.061859,0.058992,0.894542,14.460882,1.0,0.054913,8.895877,0.996568,0.857270,0.887588,0.924096
2298,"(MACBOOK, 1-4, QHD+)",(gpu_family_Apple_GPU),0.060456,0.061859,0.054051,0.894046,14.452869,1.0,0.050311,8.854260,0.990704,0.791778,0.887060,0.883907
6564,"(1-4, QHD+, MACBOOK)","(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.060456,0.061859,0.054051,0.894046,14.452869,1.0,0.050311,8.854260,0.990704,0.791778,0.887060,0.883907

### Experiment 2-1: Apriori Results Detailed Family Analysis (Apple-Dominated)

**Ultra-High Lift Rules (Lift > 14):**

| Antecedent | Consequent | Conf. | Lift |
|------------|------------|-------|------|
| 1-4 cores, QHD+, Integrated | MacBook, Apple_GPU | 89.7% | 15.2 |
| Apple_GPU, QHD+ | 1-4 cores, Integrated, MacBook | **99.9%** | 15.1 |
| MacBook, Apple_GPU | 1-4 cores, QHD+ | 91.6% | 15.1 |

**Critical Observation:** All top rules involve Apple/MacBook.

**Why?** Apple's consistent product configurations (fixed specs per model) create extremely strong patterns. Windows laptops have high SKU variability, which prevents strong family-level associations.

In [ ]:
# Example run (Apriori)
# experiment 2-1
frequent_2_2, rules_2_2 = run_rules_apriori(exp_2_2, min_support=0.05, min_confidence=0.5, min_lift=1.05)
print("\nTop rules - Experiment 2-2 (Apriori)")
display(rules_2_2)

Top rules - Experiment 2-2 (Apriori)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4819,"(1-4, QHD+, dedicated_gpu_Integrated)",(gpu_family_Apple_GPU),0.060273,0.061859,0.054112,0.897773,14.513116,1.0,0.050383,9.177058,0.990817,0.795516,0.891033,0.886263
4826,(gpu_family_Apple_GPU),"(1-4, QHD+, dedicated_gpu_Integrated)",0.061859,0.060273,0.054112,0.874753,14.513116,1.0,0.050383,7.503015,0.992492,0.795516,0.866720,0.886263
1256,"(1-4, QHD+)",(gpu_family_Apple_GPU),0.060578,0.061859,0.054112,0.893253,14.440039,1.0,0.050364,8.788430,0.990767,0.791964,0.886214,0.884003
4822,"(1-4, QHD+)","(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.060578,0.061859,0.054112,0.893253,14.440039,1.0,0.050364,8.788430,0.990767,0.791964,0.886214,0.884003
1258,(gpu_family_Apple_GPU),"(1-4, QHD+)",0.061859,0.060578,0.054112,0.874753,14.440039,1.0,0.050364,7.500579,0.992120,0.791964,0.866677,0.884003
4824,"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)","(1-4, QHD+)",0.061859,0.060578,0.054112,0.874753,14.440039,1.0,0.050364,7.500579,0.992120,0.791964,0.866677,0.884003
1263,(gpu_family_Apple_GPU),"(dedicated_gpu_Integrated, QHD+)",0.061859,0.073389,0.054112,0.874753,11.919334,1.0,0.049572,7.398292,0.976509,0.666917,0.864834,0.806038
4821,"(1-4, gpu_family_Apple_GPU)","(dedicated_gpu_Integrated, QHD+)",0.061859,0.073389,0.054112,0.874753,11.919334,1.0,0.049572,7.398292,0.976509,0.666917,0.864834,0.806038
1261,"(dedicated_gpu_Integrated, QHD+)",(gpu_family_Apple_GPU),0.073389,0.061859,0.054112,0.737323,11.919334,1.0,0.049572,3.571465,0.988660,0.666917,0.720003,0.806038
4825,"(dedicated_gpu_Integrated, QHD+)","(1-4, gpu_family_Apple_GPU)",0.073389,0.061859,0.054112,0.737323,11.919334,1.0,0.049572,3.571465,0.988660,0.666917,0.720003,0.806038
124,(gpu_family_Apple_GPU),(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
1255,"(1-4, gpu_family_Apple_GPU)",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
1260,"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
4818,"(1-4, gpu_family_Apple_GPU, dedicated_gpu_Inte...",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
125,(QHD+),(gpu_family_Apple_GPU),0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
1259,(QHD+),"(1-4, gpu_family_Apple_GPU)",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
1264,(QHD+),"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
4827,(QHD+),"(1-4, gpu_family_Apple_GPU, dedicated_gpu_Inte...",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
1357,(gpu_family_Apple_GPU),"(1-4, dedicated_gpu_Integrated)",0.061859,0.127928,0.061859,1.000000,7.816881,1.0,0.053946,inf,0.929575,0.483548,1.000000,0.741774
4823,"(gpu_family_Apple_GPU, QHD+)","(1-4, dedicated_gpu_Integrated)",0.054112,0.127928,0.054112,1.000000,7.816881,1.0,0.047189,inf,0.921961,0.422985,1.000000,0.711493

In [ ]:
# Example run (FP-Growth)
# experiment 1-1
fp_frequent_1_1, fp_rules_1_1 = run_rules_fpgrowth(exp_1_1, min_support=0.05, min_confidence=0.6, min_lift=1.1)
print("\nTop rules - Experiment 1-1 (FP-Growth)")
display(fp_rules_1_1)

Top rules - Experiment 1-1 (FP-Growth)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
10505,"(QHD+, 13-14"")",(MACBOOK),0.071437,0.101452,0.068814,0.963279,9.494933,1.0,0.061567,24.469763,0.963511,0.661196,0.959133,0.820786
10506,(MACBOOK),"(QHD+, 13-14"")",0.101452,0.071437,0.068814,0.678292,9.494933,1.0,0.061567,2.886355,0.995696,0.661196,0.653542,0.820786
10513,"(dedicated_gpu_Integrated, QHD+, 13-14"")",(MACBOOK),0.053624,0.101452,0.051306,0.956769,9.430763,1.0,0.045865,20.784836,0.944618,0.494415,0.951888,0.731241
10518,"(dedicated_gpu_Integrated, QHD+)",(MACBOOK),0.073389,0.101452,0.070095,0.955112,9.414431,1.0,0.062650,20.017654,0.964569,0.669190,0.950044,0.823016
10522,(MACBOOK),"(dedicated_gpu_Integrated, QHD+)",0.101452,0.073389,0.070095,0.690920,9.414431,1.0,0.062650,2.997964,0.994694,0.669190,0.666440,0.823016
10516,"(dedicated_gpu_Integrated, QHD+)","(MACBOOK, 13-14"")",0.073389,0.074366,0.051306,0.699086,9.400666,1.0,0.045848,3.076073,0.964401,0.531942,0.674910,0.694498
10515,"(MACBOOK, 13-14"")","(dedicated_gpu_Integrated, QHD+)",0.074366,0.073389,0.051306,0.689910,9.400666,1.0,0.045848,2.988196,0.965418,0.531942,0.665350,0.694498
10517,"(QHD+, 13-14"")","(MACBOOK, dedicated_gpu_Integrated)",0.071437,0.076745,0.051306,0.718190,9.358159,1.0,0.045823,3.276157,0.961854,0.529597,0.694764,0.693356
10514,"(MACBOOK, dedicated_gpu_Integrated)","(QHD+, 13-14"")",0.076745,0.071437,0.051306,0.668521,9.358159,1.0,0.045823,2.801276,0.967383,0.529597,0.643020,0.693356
10504,"(MACBOOK, 13-14"")",(QHD+),0.074366,0.104929,0.068814,0.925349,8.818788,1.0,0.061011,11.990014,0.957836,0.622860,0.916597,0.790581
10507,(QHD+),"(MACBOOK, 13-14"")",0.104929,0.074366,0.068814,0.655814,8.818788,1.0,0.061011,2.689343,0.990543,0.622860,0.628162,0.790581
10512,"(MACBOOK, dedicated_gpu_Integrated, 13-14"")",(QHD+),0.055515,0.104929,0.051306,0.924176,8.807611,1.0,0.045480,11.804556,0.938566,0.470095,0.915287,0.706565
10557,(LPDDR5/LPDDR5X),"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.069302,0.084553,0.051245,0.739437,8.745198,1.0,0.045385,3.513335,0.951599,0.499405,0.715370,0.672749
10555,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",(LPDDR5/LPDDR5X),0.084553,0.069302,0.051245,0.606061,8.745198,1.0,0.045385,2.362541,0.967453,0.499405,0.576727,0.672749
10499,(MACBOOK),(QHD+),0.101452,0.104929,0.092911,0.915815,8.727928,1.0,0.082266,10.632162,0.985396,0.818817,0.905946,0.900640
10500,(QHD+),(MACBOOK),0.104929,0.101452,0.092911,0.885465,8.727928,1.0,0.082266,7.845191,0.989224,0.818817,0.872533,0.900640
10521,(QHD+),"(dedicated_gpu_Integrated, MACBOOK)",0.104929,0.076745,0.070095,0.668023,8.704481,1.0,0.062042,2.781084,0.988879,0.628212,0.640428,0.790689
10519,"(dedicated_gpu_Integrated, MACBOOK)",(QHD+),0.076745,0.104929,0.070095,0.913355,8.704481,1.0,0.062042,10.330266,0.958691,0.628212,0.903197,0.790689
3149,"(dedicated_gpu_Integrated, gpu_tier_Mid_Range)","(cpu_tier_Mid_Range, 13-14"")",0.084553,0.076623,0.051672,0.611111,7.975584,1.0,0.045193,2.374399,0.955400,0.471866,0.578841,0.642737
3150,"(cpu_tier_Mid_Range, 13-14"")","(dedicated_gpu_Integrated, gpu_tier_Mid_Range)",0.076623,0.084553,0.051672,0.674363,7.975584,1.0,0.045193,2.811249,0.947194,0.471866,0.644286,0.642737

## Experiment 1-1: FP-Growth Validation

**Result:** FP-Growth produced identical rules to Apriori, confirming the discovered patterns are statistically robust.

**Algorithm Comparison:**
- Same 20 rules discovered
- FP-Growth was faster due to tree-based approach
- Both algorithms validate the Apple ecosystem dominance

In [ ]:
# Example run (FP-Growth)
# experiment 1-2
fp_frequent_1_2, fp_rules_1_2 = run_rules_fpgrowth(exp_1_2, min_support=0.05, min_confidence=0.6, min_lift=1.1)
print("\nTop rules - Experiment 1-2 (FP-Growth)")
display(fp_rules_1_2)

## Experiment 1-2: FP-Growth Validation

**Identical results confirmed.** Key patterns:
- 16GB RAM is the de facto standard for dedicated GPU laptops (82% confidence)
- DDR5 + Mid-Range GPU → Dedicated GPU (77% confidence)
- FHD + Mid-GPU + 14-15.6" → Dedicated GPU (94% confidence)

**Market Implication:** Mid-range gaming laptops have highly standardized configurations.

In [ ]:
# Example run (FP-Growth)
# experiment 2-1
fp_frequent_2_1, fp_rules_2_1 = run_rules_fpgrowth(exp_2_1, min_support=0.05, min_confidence=0.5, min_lift=1.05)
print("\nTop rules - Experiment 2-1 (FP-Growth)")
display(fp_rules_2_1)

Top rules - Experiment 2-1 (FP-Growth)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
18333,"(1-4, QHD+, dedicated_gpu_Integrated)","(MACBOOK, gpu_family_Apple_GPU)",0.060273,0.058992,0.054051,0.896761,15.201353,1.0,0.050495,9.114860,0.994136,0.828812,0.890289,0.906498
18351,"(MACBOOK, gpu_family_Apple_GPU)","(1-4, QHD+, dedicated_gpu_Integrated)",0.058992,0.060273,0.054051,0.916236,15.201353,1.0,0.050495,11.218713,0.992783,0.828812,0.910863,0.906498
18350,"(gpu_family_Apple_GPU, QHD+)","(1-4, dedicated_gpu_Integrated, MACBOOK)",0.054112,0.065947,0.054051,0.998873,15.146642,1.0,0.050482,828.505185,0.987409,0.818854,0.998793,0.909242
18334,"(1-4, dedicated_gpu_Integrated, MACBOOK)","(gpu_family_Apple_GPU, QHD+)",0.065947,0.054112,0.054051,0.819611,15.146642,1.0,0.050482,5.243616,0.999920,0.818854,0.809292,0.909242
18319,"(MACBOOK, gpu_family_Apple_GPU)","(1-4, QHD+)",0.058992,0.060578,0.054051,0.916236,15.124811,1.0,0.050477,11.215071,0.992429,0.824953,0.910834,0.904241
18341,"(dedicated_gpu_Integrated, gpu_family_Apple_GP...","(1-4, QHD+)",0.058992,0.060578,0.054051,0.916236,15.124811,1.0,0.050477,11.215071,0.992429,0.824953,0.910834,0.904241
18324,"(1-4, QHD+)","(MACBOOK, gpu_family_Apple_GPU)",0.060578,0.058992,0.054051,0.892246,15.124811,1.0,0.050477,8.732904,0.994105,0.824953,0.885491,0.904241
18343,"(1-4, QHD+)","(dedicated_gpu_Integrated, gpu_family_Apple_GP...",0.060578,0.058992,0.054051,0.892246,15.124811,1.0,0.050477,8.732904,0.994105,0.824953,0.885491,0.904241
18321,"(MACBOOK, 1-4)","(gpu_family_Apple_GPU, QHD+)",0.066252,0.054112,0.054051,0.815838,15.076906,1.0,0.050466,5.136173,0.999920,0.815087,0.805303,0.907355
18344,"(1-4, MACBOOK)","(dedicated_gpu_Integrated, gpu_family_Apple_GP...",0.066252,0.054112,0.054051,0.815838,15.076906,1.0,0.050466,5.136173,0.999920,0.815087,0.805303,0.907355
18322,"(gpu_family_Apple_GPU, QHD+)","(MACBOOK, 1-4)",0.054112,0.066252,0.054051,0.998873,15.076906,1.0,0.050466,828.234627,0.987086,0.815087,0.998793,0.907355
18340,"(dedicated_gpu_Integrated, gpu_family_Apple_GP...","(1-4, MACBOOK)",0.054112,0.066252,0.054051,0.998873,15.076906,1.0,0.050466,828.234627,0.987086,0.815087,0.998793,0.907355
18354,(gpu_family_Apple_GPU),"(1-4, QHD+, dedicated_gpu_Integrated, MACBOOK)",0.061859,0.060151,0.054051,0.873767,14.526159,1.0,0.050330,7.445364,0.992558,0.795332,0.865688,0.886174
18328,"(1-4, QHD+, dedicated_gpu_Integrated, MACBOOK)",(gpu_family_Apple_GPU),0.060151,0.061859,0.054051,0.898580,14.526159,1.0,0.050330,9.250066,0.990754,0.795332,0.891893,0.886174
18293,"(dedicated_gpu_Integrated, 1-4, QHD+)",(gpu_family_Apple_GPU),0.060273,0.061859,0.054112,0.897773,14.513116,1.0,0.050383,9.177058,0.990817,0.795516,0.891033,0.886263
18300,(gpu_family_Apple_GPU),"(dedicated_gpu_Integrated, 1-4, QHD+)",0.061859,0.060273,0.054112,0.874753,14.513116,1.0,0.050383,7.503015,0.992492,0.795516,0.866720,0.886263
18274,(gpu_family_Apple_GPU),"(MACBOOK, 1-4, dedicated_gpu_Integrated)",0.061859,0.065947,0.058992,0.953649,14.460882,1.0,0.054913,20.151701,0.992227,0.857270,0.950376,0.924096
18266,"(MACBOOK, 1-4, dedicated_gpu_Integrated)",(gpu_family_Apple_GPU),0.065947,0.061859,0.058992,0.894542,14.460882,1.0,0.054913,8.895877,0.996568,0.857270,0.887588,0.924096
18317,"(MACBOOK, 1-4, QHD+)",(gpu_family_Apple_GPU),0.060456,0.061859,0.054051,0.894046,14.452869,1.0,0.050311,8.854260,0.990704,0.791778,0.887060,0.883907
18336,"(1-4, QHD+, MACBOOK)","(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.060456,0.061859,0.054051,0.894046,14.452869,1.0,0.050311,8.854260,0.990704,0.791778,0.887060,0.883907

## Experiment 2-1: FP-Growth Validation

**Same Apple-dominated rules confirmed.**

**Business Insight:** Apple's product strategy (limited SKUs, consistent specs) enables 99%+ confidence rules. This is a competitive advantage for brand recognition.

**Implication for Windows OEMs:** Reducing product variety could strengthen brand patterns in customer perception.

In [ ]:
# Example run (FP-Growth)
# experiment 2-1
fp_frequent_2_2, fp_rules_2_2 = run_rules_fpgrowth(exp_2_2, min_support=0.05, min_confidence=0.5, min_lift=1.05)
print("\nTop rules - Experiment 2-2 (FP-Growth)")
display(fp_rules_2_2)

Top rules - Experiment 2-2 (FP-Growth)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
17194,"(1-4, QHD+, dedicated_gpu_Integrated)",(gpu_family_Apple_GPU),0.060273,0.061859,0.054112,0.897773,14.513116,1.0,0.050383,9.177058,0.990817,0.795516,0.891033,0.886263
17201,(gpu_family_Apple_GPU),"(1-4, QHD+, dedicated_gpu_Integrated)",0.061859,0.060273,0.054112,0.874753,14.513116,1.0,0.050383,7.503015,0.992492,0.795516,0.866720,0.886263
17183,"(1-4, QHD+)",(gpu_family_Apple_GPU),0.060578,0.061859,0.054112,0.893253,14.440039,1.0,0.050364,8.788430,0.990767,0.791964,0.886214,0.884003
17197,"(1-4, QHD+)","(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.060578,0.061859,0.054112,0.893253,14.440039,1.0,0.050364,8.788430,0.990767,0.791964,0.886214,0.884003
17185,(gpu_family_Apple_GPU),"(1-4, QHD+)",0.061859,0.060578,0.054112,0.874753,14.440039,1.0,0.050364,7.500579,0.992120,0.791964,0.866677,0.884003
17199,"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)","(1-4, QHD+)",0.061859,0.060578,0.054112,0.874753,14.440039,1.0,0.050364,7.500579,0.992120,0.791964,0.866677,0.884003
17190,(gpu_family_Apple_GPU),"(dedicated_gpu_Integrated, QHD+)",0.061859,0.073389,0.054112,0.874753,11.919334,1.0,0.049572,7.398292,0.976509,0.666917,0.864834,0.806038
17196,"(1-4, gpu_family_Apple_GPU)","(dedicated_gpu_Integrated, QHD+)",0.061859,0.073389,0.054112,0.874753,11.919334,1.0,0.049572,7.398292,0.976509,0.666917,0.864834,0.806038
17188,"(dedicated_gpu_Integrated, QHD+)",(gpu_family_Apple_GPU),0.073389,0.061859,0.054112,0.737323,11.919334,1.0,0.049572,3.571465,0.988660,0.666917,0.720003,0.806038
17200,"(dedicated_gpu_Integrated, QHD+)","(1-4, gpu_family_Apple_GPU)",0.073389,0.061859,0.054112,0.737323,11.919334,1.0,0.049572,3.571465,0.988660,0.666917,0.720003,0.806038
17177,(gpu_family_Apple_GPU),(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
17182,"(1-4, gpu_family_Apple_GPU)",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
17187,"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
17193,"(1-4, gpu_family_Apple_GPU, dedicated_gpu_Inte...",(QHD+),0.061859,0.104929,0.054112,0.874753,8.336604,1.0,0.047621,7.146471,0.938076,0.480238,0.860071,0.695226
17178,(QHD+),(gpu_family_Apple_GPU),0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
17186,(QHD+),"(1-4, gpu_family_Apple_GPU)",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
17191,(QHD+),"(dedicated_gpu_Integrated, gpu_family_Apple_GPU)",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
17202,(QHD+),"(1-4, gpu_family_Apple_GPU, dedicated_gpu_Inte...",0.104929,0.061859,0.054112,0.515698,8.336604,1.0,0.047621,1.937097,0.983215,0.480238,0.483764,0.695226
17181,(gpu_family_Apple_GPU),"(1-4, dedicated_gpu_Integrated)",0.061859,0.127928,0.061859,1.000000,7.816881,1.0,0.053946,inf,0.929575,0.483548,1.000000,0.741774
17198,"(gpu_family_Apple_GPU, QHD+)","(1-4, dedicated_gpu_Integrated)",0.054112,0.127928,0.054112,1.000000,7.816881,1.0,0.047189,inf,0.921961,0.422985,1.000000,0.711493

### Experiment 2-2: For both algorithms : Extended Family Analysis

Similar to Experiment 2-1, rules are Apple-centric. The detailed CPU/GPU family features only produce strong patterns for Apple products.

**Conclusion:** For Windows laptops, tier-based analysis (Experiment 1) provides more actionable insights than family-based analysis (Experiment 2).

In [ ]:
import plotly.express as px

# Combine all rules for visualization
all_rules = []
for rules_df, label in [
    (rules_1_1, 'Exp 1-1 Apriori'), (rules_1_2, 'Exp 1-2 Apriori'),
    (fp_rules_1_1, 'Exp 1-1 FP-Growth'), (fp_rules_1_2, 'Exp 1-2 FP-Growth'),
    (fp_rules_2_1, 'Exp 2-1 FP-Growth'), (fp_rules_2_2, 'Exp 2-2 FP-Growth'),
]:
    if rules_df is not None and len(rules_df) > 0:
        tmp = rules_df.copy()
        tmp['experiment'] = label
        tmp['antecedents'] = tmp['antecedents'].astype(str)
        tmp['consequents'] = tmp['consequents'].astype(str)
        all_rules.append(tmp)

if all_rules:
    combined = pd.concat(all_rules, ignore_index=True)
    fig = px.scatter(
        combined, x='support', y='confidence', color='lift',
        size='lift', hover_data=['antecedents', 'consequents', 'experiment'],
        title='Association Rules: Support vs Confidence (colored by lift)',
        color_continuous_scale='Viridis',
    )
    fig.show()
else:
    print('No rules to visualize')

In [ ]:
# export the results as csv to anlyze them
rules_1_1.to_csv('reports/rules/rules_1_1_apriori.csv', index=False)
rules_1_2.to_csv('reports/rules/rules_1_2_apriori.csv', index=False)
rules_2_1.to_csv('reports/rules/rules_2_1_apriori.csv', index=False)
rules_2_2.to_csv('reports/rules/rules_2_2_apriori.csv', index=False)
fp_rules_1_1.to_csv('reports/rules/rules_1_1_fpgrowth.csv', index=False)
fp_rules_1_2.to_csv('reports/rules/rules_1_2_fpgrowth.csv', index=False)
fp_rules_2_1.to_csv('reports/rules/rules_2_1_fpgrowth.csv', index=False)
fp_rules_2_2.to_csv('reports/rules/rules_2_2_fpgrowth.csv', index=False)
print("\nRules exported to CSV files.")

Rules exported to CSV files.

## Key Summary: Association Rules Mining

### Objective
Discover frequent hardware configuration patterns using **Apriori** and **FP-Growth** algorithms on 16,392 laptop listings.

### Main Discovery
**Apple dominates premium compact displays:** 96% of laptops with QHD+ + 13-14" screen are MacBooks (Lift 9.5).

### Three Market Segments Identified

| Segment | Configuration | Confidence |
|---------|--------------|------------|
| **Apple Premium** | 13-14", QHD+, Integrated GPU, LPDDR5 | 96% |
| **Business Ultrabook** | 13-14", FHD, Integrated GPU, Mid-CPU | 68% |
| **Gaming Laptop** | 15.6", FHD, Dedicated GPU, 16GB RAM | 94% |

### Top Association Rules

| Rule | Confidence | Lift |
|------|------------|------|
| {QHD+, 13-14"} → {MacBook} | **96.3%** | 9.49 |
| {LPDDR5} → {Integrated GPU, Mid-Tier} | 73.9% | 8.75 |
| {FHD, Mid-GPU, 15.6"} → {Dedicated GPU} | 93.8% | 4.75 |

### Key Takeaway
> Apple's consistent product configurations enable **99% confidence rules**, while Windows laptop variety requires **tier-level analysis** for meaningful patterns.

### Business Recommendations
- **Retailers:** Stock standard gaming configs (16GB + 512GB SSD + FHD)
- **Manufacturers:** Premium 13-14" QHD+ Windows laptops = market gap
- **Insight:** Gaming prioritizes FHD (frame rate) over 4K (resolution)